title: Noah Morrison
email: noah@morrison.ph
description: >-
  Photography, social links, and any other hobbies I get
baseurl: ""
url: "https://noah.morrison.ph"
github_username:  noahmorrison

# Build settings
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - compose.yaml
  - tests
  - test-results
