title: Noah Morrison
email: noah@morrison.ph
description: >-
  Personal website for Noah Morrison
baseurl: ""
url: "https://noah.morrison.ph"
github_username:  noahmorrison

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - compose.yaml
  - tests
  - test-results
